:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2016.1
:: Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
:: 
:: ==============================================================


@echo off

C:/Xilinx/Vivado_HLS/2016.1/../../Vivado/2016.1/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7a200tfbg676-2 ../xilinx_com_hls_cmp_max_1_0.zip
