// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module cmp_max_top (
aresetn,
aclk,
y0,
y1,
y2,
max,
max_ap_vld,
en,
ap_start,
ap_ready,
ap_done,
ap_idle
);

parameter RESET_ACTIVE_LOW = 1;
input aresetn ;

input aclk ;

input [32 - 1:0] y0 ;
input [32 - 1:0] y1 ;
input [32 - 1:0] y2 ;
output [32 - 1:0] max ;
output max_ap_vld ;
input [1 - 1:0] en ;
input ap_start ;
output ap_ready ;
output ap_done ;
output ap_idle ;

wire aresetn;


wire sig_cmp_max_ap_rst;



cmp_max cmp_max_U(
    .ap_rst(sig_cmp_max_ap_rst),
    .ap_clk(aclk),
    .y0(y0),
    .y1(y1),
    .y2(y2),
    .max(max),
    .max_ap_vld(max_ap_vld),
    .en(en),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

cmp_max_ap_rst_if #(
    .RESET_ACTIVE_LOW(RESET_ACTIVE_LOW))
ap_rst_if_U(
    .dout(sig_cmp_max_ap_rst),
    .din(aresetn));

endmodule
